### ISSUE TITLE
The codes cannot run in the current form.

### ISSUE THREAD

**Issue by jsdaiustc** [ml-postech/robust-deep-learning-from-crowds-with-belief-propagation#1]
Lines 27-28 in dataset.py require two files 'data.npy' and 'labels.npy'. 

Could the authors provide some examples for these two files? Thank you very much.

**Comment by seunghyukcho** [comment]
Hello! 

Thank you for using our code. You can find a sample of the files in [here](https://drive.google.com/file/d/1FqyQGgfT5eUQ-l6e54a4GZOqjKejUl-F/view?usp=sharing). This is the preprocessed dataset of 'Dogs vs Cats' which is used in our paper experiments.

**Comment by jsdaiustc** [comment]
Thanks a lot for your help. It is a very interesting work.
