### ISSUE TITLE
BP algorithm

### ISSUE THREAD

**Issue by ZhouCX117** [ml-postech/robust-deep-learning-from-crowds-with-belief-propagation#2]
Thanks for your excellent work! After reading your code, I find that understanding BP iteration is too hard for me. Do you have any literation for me to read? I don't understand the calculation process. Thanks a lot! Looking forward to your answer!

**Comment by seunghyukcho** [comment]
Hello! I'll give you some instructions to understand our BP iteration code.

1. Assume that all the annotations are available (a complete graph).
2. Then, implement the BP iterations of our paper using for-loops. If you consider using for-loops, it will be easier to implement your own BP iterations.
3. Compare the for-loop based BP iterations and our implementation. You can find that changing the for-loops to matrix multiplication is what we done.
4. Remove the assumption at (1). You can remove the assumption from the code by masking some variables, where the mask is implemented as (ann == -1) in our code.

Thank you for enjoying our work. We feel free to discuss with you if you have more questions about our code!
